### ISSUE TITLE
squash_option is not being honored

### ISSUE THREAD

**Issue by vchepkov** [gdubicki/gitlabform#264]
setting project's squash_option to default_on or default_off has no effect, setting is not changed in the gitlab

Gitlab version: 13.12.5-ee

$ gitlabform -V
🏗  GitLabForm version: 2.2.0 = the latest stable 😊

**Comment by gdubicki** [comment]
Hi @vchepkov !

Thanks for reporting the issue but can you please elaborate what do you mean by "setting is not changed in the gitlab"? 

Because I added a test that checks that the default value for this is "default_off" and after using GitLabForm it is correctly set to "default_on" - see the link above.

A config sample or some screenshots would help.

**Comment by qstorey** [comment]
I'm experiencing a similar issue:

```yaml
    project_settings:
      merge_method: ff
      squash_option: always
      ...
```

When I view the project in GitLab the `Merge method` is set to `Fast-forward merge`, but the `Squash commits when merging` settings remains on the default of `Allow`.

**Comment by qstorey** [comment]
After a bit more investigation it would appear the `squash_option` was only introduced into the API GitLab 14.0. See [MR](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/63543).

I'm currently using self hosted GitLab 13.8.8 so that explains why I am experiencing this issue.

**Comment by vchepkov** [comment]
That explains it, sorry for the noise, will have to wait for upgrade

**Comment by vchepkov** [comment]
We have upgraded gitlab to v14.0.10 and yet setting is still not being honored

Here is the part of the config:

```
projects_and_groups:
  "it/*":
    project_settings:
      only_allow_merge_if_all_discussions_are_resolved: true
      only_allow_merge_if_pipeline_succeeds: true
      allow_merge_on_skipped_pipeline: false
      autoclose_referenced_issues: false
      squash_option: default_off
      merge_method: ff
      remove_source_branch_after_merge: true
```

Running gitlabform 2.5.0 and squash_option remains in Encourage state, instead of Allow
