### ISSUE TITLE
Allow breaking configuration inheritence

### ISSUE THREAD

**Issue by amimas** [gdubicki/gitlabform#326]
I've started using the v2 (2.10.0). Lots of improvements have been made from v1. This post is a feature request for being able to break config inheritance.

Below is an example config of what it might look like for a typical group.

```yml
config_version: 2
gitlab:
  api_version: 4

projects_and_groups:
  my-group/*:
    # Settings for ALL projects under 'my-group' group and the group itself
    group_settings:
      # Settings of the parent group
      description: Contains projects for example product.
    members:
      # Members for ALL projects.
      enforce: true
      groups:
        user-group-1:
          group_access: 30  # Developer role
        user-group-2:
          group_access: 30  # Developer role
    project_settings:
      # Settings of ALL projects
      visibility: internal
      issues_access_level: enabled
      request_access_enabled: false

  my-group/special-private-project:
    # This is a special project. It should be private and have specific user permission.
    project_settings:
      visibility: private
    members:
      # Only following users should have permission. Do not inherit permissions from common settings
      groups:
        user-group-2:
          group_access: 30
       users:
          john:
            access_level: 40
```

With the above config, the project `my-group/special-private-project` gets members from the common settings (configured in `my-group/*` section) in addition to what's configured in that project directly.

I think it makes sense that this is how it works by default. It'd be nice if I could specify in that project specific config to not inherit common settings so that I could manage "exception" scenarios. In the above example, I want to break the inheritance of the `members` section only but inherit other settings.  I guess it could be perceived that someone might want to break the inheritance in other areas/sections as well

Right now my work-around is following. Only problem with this work-around is that I need to list out every single project in the config just so that I could have exception for a single project. So, I'm not able to take full advantage/power of gitlabform's config.

```yml

config_version: 2
gitlab:
  api_version: 4

default_project_access_by_usergroup: &default-project-access-by-usergroup
  user-group1:
    group_access: 30  # Developer
  user-group2:
    group_access: 30  # Developer

projects_and_groups:
  my-group/*:
    # Settings for ALL projects under 'my-group' group and the group itself
    group_settings:
      # Settings of the parent group
      description: Contains projects for example product.
    members:
      # Members for ALL projects.
      # Leave this section empty so that each project can specify what permission to be set.
      # Otherwise we cannot configure exception using gitlabform
      enforce: true
    project_settings:
      # Settings of ALL projects
      visibility: internal
      issues_access_level: enabled
      request_access_enabled: false

  my-group/project1:
    members:
      groups:
        <<: *default-project-access-by-usergroup

  my-group/project2:
    members:
      groups:
        <<: *default-project-access-by-usergroup

  my-group/special-private-project:
    # This is a special project. It should be private and have specific user permission.
    project_settings:
      visibility: private
    members:
      # Only following users should have permission. Do not inherit permissions from common settings
      groups:
        user-group-2:
          group_access: 30
       users:
          john:
            access_level: 40
```

**Comment by gdubicki** [comment]
Hi @amimas!

Sorry for a late reply. We actually run into this need too, so I will probably implement it soon. Unless you’d like to give it a try?

**Comment by amimas** [comment]
Hi @gdubicki - Thanks for acknowledging this request. I believe my colleague @ep-linden can look into implementing it. Can you give us some guidance? What should we name this config and any suggestions how to implement it? I imagine this is something that should be available at every level of the configs (i.e. project_settings, members, merge_requests, etc.)

**Comment by gdubicki** [comment]
As we already have special keywords like `delete: true`, `enforce: true` I suggest another single-word keyword - `inherit: false`.

So for your example case, the config (shortened to include only the membership) would look like this:
```
projects_and_groups:
  my-group/*:
    members:
      enforce: true
      groups:
        user-group-1:
          group_access: developer
        user-group-2:
          group_access: developer
 
  my-group/special-private-project:
    members:
      inherit: false
      enforce: true
      groups:
        user-group-2:
          group_access: developer
      users:
        john:
          access_level: maintainer
```

As you suggested, the `inherit: false` would apply only to a single section where it is included. If you want to break inheritance for more sections then you should put this key and value explicitly in each one of them.

Also breaking inheritance would only work _from the top to the specific level_.

Example: imagine that we have a config `a` for `*/*`, config `b` for `group/*` and config `c` for `group/project`.
Without any inheritance breaking the `group/project` has config `a+b+c` (where `+` is merging).

If you set `inherit: false` in the config `a`, then we should throw an error as it would effectively not do anything as there is nothing to not inherit from and it would be misleading to allow such config.

If you set `inherit: false` in the config `b`, then `group/project` has only config `b+c` (`a` is not inherited).

If you set `inherit: false` in the config `c`, then `group/project` has only config `c` (`a` and `b` are not inherited).

Does that make sense, @amimas @ep-linden?

If so, then I think that we only need to update [the `merge_configs()` method](http://github.com/gdubicki/gitlabform/blob/b7fe98349537b7e1f7996e8c99b36f4f5b49aa52/gitlabform/configuration/core.py#L166-L171) to implement this (+ some tests, of course). This should not be hard, just keep in mind that this method operates on a whole config for f.e. group or project, not just a single section.

**Comment by amimas** [comment]
Thanks for all that details @gdubicki . That makes sense to me and is also what I was thinking how this feature would work.

Question on the config keyword, `inherit`. Could this be confused with how inheritance work in gitlab (i.e. group -> sub-group/project), etc. For example: in the case of not inheriting member configuration, would it seem like we're trying to break the configuration in gitlab? For members, this is not possible. If a user is added at the group level, you can't remove them from a project.

Maybe I'm over thinking this? Perhaps it's not going to be confusing because the users of gitlabform is expected to have certain knowledge about how gitlab works.

Thoughts?

**Comment by gdubicki** [comment]
> Question on the config keyword, `inherit` (..)

Yes, there is a slight naming clash here with gitlab's terminology and this is not perfect. But "inheritance" is also a term [used in gitlabform from the start](https://github.com/gdubicki/gitlabform/blob/main/docs/FEATURES_DESIGN.md#hierarchical-merged-and-overridable-configuration) and I frankly don't have any alternative ideas.. Do you have?

Anyway, this is something we can agree on later (maybe someone else will chip in?) - it should not block you from creating the PR. :)

**Comment by amimas** [comment]
> But "inheritance" is also a term [used in gitlabform from the start](https://github.com/gdubicki/gitlabform/blob/main/docs/FEATURES_DESIGN.md#hierarchical-merged-and-overridable-configuration)

That's a good point. I couldn't think of an alternative either. And I agree this can be improved later, if needed.

**Comment by jccl** [comment]
> Yes, there is a slight naming clash here with gitlab's terminology and this is not perfect. But "inheritance" is also a term [used in gitlabform from the start](https://github.com/gdubicki/gitlabform/blob/main/docs/FEATURES_DESIGN.md#hierarchical-merged-and-overridable-configuration) and I frankly don't have any alternative ideas.. Do you have?

In the Maven POM world, the merging of XML behaviour that works similar to what's being requested here is controlled by an attribute called `combine.self`. By default the attribute value is `merge`, but you can set it to `override` to have the desired behaviour of overriding the inheritance.

How's something along the lines of `combine_self` for the key word to avoid clashing?

Here's how it might look:
```
projects_and_groups:
  my-group/*:
    members:
      groups:
        user-group-1:
          group_access: developer
 
  my-group/special-private-project:
    members:
      combine_self: override
      enforce: true
      users:
        john:
          access_level: maintainer
```
