### ISSUE TITLE
Allow for same "level" to exist multiple times

### ISSUE THREAD

**Issue by lfvjimisola** [gdubicki/gitlabform#327]
I would like to be able to specify a label multiple times in order to structure up the configuration.

The example below will fail with "ERROR:  Duplicate Hash key detected:".

E.g.

```
projects_and_groups:

# wiki_access_level
  group1:
    project_settings:
      "wiki_access_level": "disabled"
  "group1/some_project":
    project_settings:
      "wiki_access_level": "enabled"

# some other setting
  group1:
    project_settings:
      "xyz": true
  "group1//true_for_all_but_this_project":
    project_settings:
      "xyz": false


```

**Comment by gdubicki** [comment]
Hi @lfvjimisola!

Would accepting multiple configuration files fulfill your needs? Because we already have a request for it here #13 and it should be pretty easy to implement. We are open to PRs with it! :)

**Comment by lfvjimisola** [comment]
@gdubicki It'll work as a workaround. But, I'd prefer to have it in one file over time. The file format seem oto need an upgrade:

* keys are just placeholder names
* matching of groups/projects can be done in different ways such as on id/name and regexp on pathname.

  "wiki access":
     - include:
          groupIds: [ 213, 99 ]
          groupNames: [ "name1", "name2" ]
          projectIds: [ 2, 3, 5 ]
          regexp: [ "someregexp" ]
     - exclude:
          groupIds: [ 13, 9 ]
          groupNames: [ "name4", "name5" ]
          projectIds: [ 173 ]
          regexp: [ "someregexp" ]

  "merge requests etc":
     - include:
          groupIds: [ 213, 99 ]
          groupNames: [ "name1", "name2" ]
          projectIds: [ 2, 3, 5 ]
          regexp: [ "someregexp" ]
     - exclude:
          groupIds: [ 13, 9 ]
          groupNames: [ "name4", "name5" ]
          projectIds: [ 173 ]
          regexp: [ "someregexp" ]

**Comment by lfvjimisola** [comment]
Maybe it would be wise to connect/label all issues that relates to the format of configuration somehow?
It think that this is extremely important in order to allow flexibility with DRY (Don't Repeat Yourself).

List of issues that I found:

- https://github.com/gdubicki/gitlabform/issues/326
- https://github.com/gdubicki/gitlabform/issues/326
- https://github.com/gdubicki/gitlabform/issues/326
- https://github.com/gdubicki/gitlabform/issues/254
- https://github.com/gdubicki/gitlabform/issues/139
- https://github.com/gdubicki/gitlabform/pull/138
- https://github.com/gdubicki/gitlabform/issues/112
- https://github.com/gdubicki/gitlabform/issues/105
- https://github.com/gdubicki/gitlabform/issues/105
- https://github.com/gdubicki/gitlabform/issues/82
- https://github.com/gdubicki/gitlabform/issues/13

**Comment by gdubicki** [comment]
> @gdubicki It'll work as a workaround - if the same "key" can exist in the different files (and not as mentioned here [#13 (comment)](https://github.com/gdubicki/gitlabform/issues/13#issue-265974506)). But, I'd prefer to have it in one file over time.

Ok, I think I understand what you need better now and I have a proposal that should fit your needs and would not break YAML standard. So how about we do this:

If the config file contains more than a single YAML document (separated with `---`) then the effective config would be created by merging each YAML document together, in the order they are provided in the file.

(Let's assume that this means that I redact [the comment from #13](https://github.com/gdubicki/gitlabform/issues/13#issue-265974506).)

This would allow you to do what you want with this config:
```
---
projects_and_groups:

# wiki_access_level
  group1/*:
    project_settings:
      "wiki_access_level": "disabled"
  "group1/some_project":
    project_settings:
      "wiki_access_level": "enabled"

---
projects_and_groups:

# some other setting
  group1/*:
    project_settings:
      "xyz": true
  "group1/true_for_all_but_this_project":
    project_settings:
      "xyz": false
```

...that would effectively work as:

```
projects_and_groups:
  group1/*:
    project_settings:
      "wiki_access_level": "disabled"
      "xyz": true
  "group1/some_project":
    project_settings:
      "wiki_access_level": "enabled"
  "group1/true_for_all_but_this_project":
    project_settings:
      "xyz": false
```

WDYT?
