### ISSUE TITLE
Error: Project or group de.smile.tools cannot be found in GitLab!

### ISSUE THREAD

**Issue by gs4711** [gdubicki/gitlabform#356]
Using the command

`docker run -it -v $(pwd):/config ghcr.io/gdubicki/gitlabform:latest gitlabform -d -n de.smile`

show a perfects list of found projects during debug mode - but in any case an error message

`Error: Project or group de.smile.tools cannot be found in GitLab!`

is displayed after the debugging information.

The configuration `config.yml ` being used is:

```
config_version: 2

gitlab:
  # You can also set in your environment GITLAB_URL
  url: https://gitlab.smile.de
  # You can also set in your environment GITLAB_TOKEN
  token: "very secret"

projects_and_groups:
  de.smile.tools.guacamole:
    # common settings for ALL projects and ALL groups
    # keys and values here are as described at https://docs.gitlab.com/ce/api/projects.html#edit-project
    project_settings:
      default_branch: main
      jobs_enabled: false
      public_jobs: false # "Public pipelines" checkbox in GitLab web UI
      visibility: private

```
